MusicStoreMVC/MusicStoreMVC/Controllers/AlbumController.cs
using System.Linq;
using System.Web.Mvc;
using MusicStoreMVC.Models;
using Repository.Abstract;

namespace MusicStoreMVC.Controllers
{
    public class AlbumController : Controller
    {
        private IAlbumRepository _repository;
        private int PageSize = 10;
        public AlbumController(IAlbumRepository repository)
        {
            _repository = repository;
        }

        public ActionResult Index()
        {
            ViewBag.Message = "Main page.";

            return View();
        }

        // GET: Album
        public ViewResult Albumy(string genre, int page = 1)
        {
            AlbumListViewModel viewModel = new AlbumListViewModel
            {
                Albums = _repository.Albums
                .Where(p=>genre==null || p.Genre==genre)
                    .OrderBy(p => p.Title)
                    .Skip((page-1)*PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = genre == null ?
                    _repository.Albums.Count() :
                    _repository.Albums.Count(p => p.Genre==genre)
                },
                CurentGenre = genre
            };
            return View(viewModel);
        }
    }
}

MusicStoreMVC/MusicStoreMVC/Views/Album/Albumy.cshtml
@using MusicStoreMVC.HtmlHelpers
@model MusicStoreMVC.Models.AlbumListViewModel

@{
    ViewBag.Title = "Albumy";
}

<h2>@Model.CurentGenre</h2>
@foreach (var item in Model.Albums)
{
	Html.RenderPartial("AlbumSummary", item);
} 

<nav>
    <ul class="pagination">
        <li>
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li>@Html.PageLinks(Model.PagingInfo, x => Url.Action("Albumy", new { page = x, genre = Model.CurentGenre }))</li>
        <li>
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

MusicStoreMVC/MusicStoreMVC/Views/Album/Index.cshtml
@using MusicStoreMVC.HtmlHelpers
@model MusicStoreMVC.Models.AlbumListViewModel

@{
    ViewBag.Title = "Index";
}

<style>
    body { background-image: url("../Content/Images/FrontSiteBg.jpg"); }
</style>

<div id="page-top">
   <header>
	<div class="animated fadeIn">
        <div class="header-content">
            <div class="header-content-inner">
				<h1>Musical Store</h1>
                <p>Znajdziesz tu przeróżne albumy muzyczne - najwięksi artysci, alternatywne płyty w atrakcyjnych cenach oraz wiele innych rozwiązań dla kolekcjonerów i casualowców.</p>
				@Html.ActionLink("Przejdz do sklepu", "Albumy", "Album", new { @class="btn btn-primary btn-xl page-scroll" })
            </div>
        </div>
	</div>
    </header>
</div>