MusicStoreMVC/MusicStoreMVC/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using Model.Entities;
using MusicStoreMVC.Models;
using Repository.Abstract;

namespace MusicStoreMVC.Controllers
{
   
    public class CartController : Controller
    {
        private IAlbumRepository _repository;

        public CartController(IAlbumRepository repository)
        {
            _repository = repository;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            CartIndexViewModel viewModel = new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            };
            return View(viewModel);
        }

        
        public RedirectToRouteResult AddToCart(Cart cart, int albumId, string returnUrl)
        {
            Album album = _repository.Albums.FirstOrDefault(x => x.AlbumId == albumId);
            if (album!=null)
            {
                cart.AddItem(album,1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart,int albumId, string returnUrl)
        {
            Album album = _repository.Albums.FirstOrDefault(x => x.AlbumId == albumId);
            if (album!=null)
            {
                cart.RemoveLine(album);
            }
            return RedirectToAction("Index", new {returnUrl});
        }

        [Authorize]
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        //Korzystamy z łącznika modelu nie musimy korzystac z metody GetCart w zamian przekazujemy parametr Cart do kazdej z metod
        //private Cart GetCart()
        //{
        //    Cart cart = (Cart)Session["Cart"];
        //    if (cart==null)
        //    {
        //        cart=new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}
    }
}

MusicStoreMVC/MusicStoreMVC/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.Entities;

namespace MusicStoreMVC.Controllers
{
    public class ContactController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult SendMessage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendMessage(ContactForm contactForm) // zrobic jeszcze wiadomosc na górze storny ze wiadomosc zostala wyslana
        {
            if (!(new EmailAddressAttribute().IsValid(contactForm.Email)))
            {
                ViewBag.Title = "Podany adres e-mial jest nieporawidłowy";
                return View("Index");
            }
            if (!ModelState.IsValid)
            {
                ViewBag.Title = "Wypełnij wszystkie pola i spróbuj ponownie";
                return View("Index");
            }

            string RecipientAddress = contactForm.Email;
            string Topic = contactForm.Topic;

            string SenderAddress = "musicStoreTorun@gmail.com";
            string SenderPassword = "Admin!12";


            string Message = "Od: " + contactForm.Email + "\n\n";
            Message += "Temat: " + contactForm.Topic + "\n\n";
            Message += "Wiadomość: " + contactForm.Message + "\n\n";

            // smtp settings
            var smtp = new System.Net.Mail.SmtpClient();
            {
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.EnableSsl = true;
                smtp.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
                smtp.Credentials = new NetworkCredential(SenderAddress, SenderPassword);
                smtp.Timeout = 20000;
            }

            smtp.Send(RecipientAddress, SenderAddress, Topic, Message);

            return RedirectToAction("Index");
        }
    }
}

MusicStoreMVC/MusicStoreMVC/Controllers/NavController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Repository.Abstract;

namespace MusicStoreMVC.Controllers
{
    public class NavController : Controller
    {
        private IAlbumRepository _repository;
        public NavController(IAlbumRepository repository)
        {
            _repository = repository;
        }
        // GET: Nav
        public PartialViewResult Menu()
        {
            IEnumerable<string> genres = _repository.Albums
                .Select(x => x.Genre)
                .Distinct();
            return PartialView(genres);
        }
    }
}

MusicStoreMVC/MusicStoreMVC/Views/Shared/AlbumSummary.cshtml
@model Model.Entities.Album

@{
    ViewBag.Title = "AlbumSummary";
}


<hr>

<div class="row">
            <div class="col-md-7">
                <a href="#">
                    <img class="img-responsive" alt="@Html.DisplayFor(model => model.Title)" src="http://placehold.it/700x300">
                </a>
            </div>
            <div class="col-md-5">
                <h3>@Html.DisplayFor(model => model.Title)</h3>
                <h4>@Html.DisplayFor(model => model.Artist)</h4>
                <p>Jeden z albumów zespołu @Html.DisplayFor(model => model.Artist) o dumnej
				nazwie @Html.DisplayFor(model => model.Title).</p>
                <p>@if (Request.IsAuthenticated)
								{
									using (Html.BeginForm("AddToCart", "Cart"))
									{
										@Html.HiddenFor(x => x.AlbumId)
										@Html.Hidden("returnUrl", Request.Url.PathAndQuery)<input type="submit" class="btn btn-info" value="+ Dodaj do koszyka"/>
									}
							}
							else
							{
								<span class="label label-danger">Zaloguj się aby kupić album!</span>
							}    
										</p>
            </div>
        </div>

<hr>

<!--<table class="table-hover">
    <tr>
        <th>
            AlbumUrl
        </th>
        <th>
            Genre
        </th>
        <th>
            Artist
        </th>
        <th>
            Title
        </th>
        <th>
            Price
        </th>
    </tr>
    <tr>
        <td>
            <img alt="@Html.DisplayFor(model => model.Title)" src="@Html.DisplayFor(model => model.AlbumUrl)" />
        </td>
        <td>
            @Html.DisplayFor(model => model.Genre)
        </td>
        <td>
            @Html.DisplayFor(model => model.Artist)
        </td>
        <td>
            @Html.DisplayFor(model => model.Title)
        </td>
        <td>
            @Html.DisplayFor(model => model.Price)
        </td>
        <td class="right">

            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("AddToCart", "Cart"))
                {
                    @Html.HiddenFor(x => x.AlbumId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)<input type="submit" class="btn btn-info" value="+ Dodaj do koszyka"/>
                }
            }
            else
            {
                <span class="label label-danger">Zaloguj się aby dodać album do koszyka!</span>
            }    
                
            
            
        </td>


    </tr>
</table> -->

MusicStoreMVC/MusicStoreMVC/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

MusicStoreMVC/MusicStoreMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
	
	<link href="@Url.Content("../Content/Bootstrap.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("../Content/Bootstrap.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("../Content/Creative.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("../Content/Creative.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("../Content/magnific-popup.css.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("../Content/Site.css")" rel="stylesheet" type="text/css" />
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href="@Url.Content("../Content/font-awesome.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("../Content/font-awesome.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("../Content/AnimateIt.css")" rel="stylesheet" type="text/css" />


	<script src="@Url.Content("../Content/bootstrap.js")" type="text/javascript"></script>
	<script src="@Url.Content("../Content/bootstrap.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("../Content/creative.js")" type="text/javascript"></script>
	<script src="@Url.Content("../Content/jquery.easing.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("../Content/jquery.fittext.js")" type="text/javascript"></script>
	<script src="@Url.Content("../jquery.js")" type="text/javascript"></script>
	<script src="@Url.Content("../jquery.magnific-popup.js")" type="text/javascript"></script>
	<script src="@Url.Content("../jquery.magnific-popup.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("../scrollreveal.js")" type="text/javascript"></script>
	<script src="@Url.Content("../scrollreveal.min.js")" type="text/javascript"></script>
	
	@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/Content/js")

</head>
<body>
   
    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
			<br>
				<li><img src="../Content/Images/logo.png" > </li>
				</br>
                <li class="sidebar-brand">
                    <a>
                        Kategorie
                    </a>
                </li>
                <li>@{Html.RenderAction("Menu", "Nav");}</li>

            </ul>
        </div>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Sklep Muzyczny", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("O nas", "About", "Home")</li>
                        <li>@Html.ActionLink("Kontakt", "Index", "Contact")</li>
                    </ul>
                   @if (Request.IsAuthenticated)
                   {
                       Html.RenderAction("Summary", "Cart");
                       
                   }
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        </div>
</body>
</html>